### PR TITLE
adds rules for notification logs

### PR DESCRIPTION
**Pull request by Crited**
refers to #15

### CODE REVIEW

**Comment by widhalmt** [comment]
Plese do not use CamelCase in field names. They all should be written in lowercase.

```
match => ["message","Type '%{WORD:[icinga][notificationtype]}', TypeFilter: %{DATA:[icinga][TypeFilter]}\(%{WORD}=%{NUMBER:[notification][FType]}, %{WORD}=%{NUMBER:[notification][TypeFilter]}\)"]
```

**Comment by Crited** [comment]
Adjusted to be compliant with all lowercase-structure. My bad.

**Comment by widhalmt** [comment]
Sorry, there's another change that must have slipped my attention in the first place. Please make all fields subfields of `icinga` . So please change `[notification]` to `[icinga][notification]`.

**Comment by Crited** [comment]
This has been stalled for a while, because of the tactical decision we had to tackle, regarding arrays, that has been resolved by this documentation update: https://github.com/widhalmt/logstash-icinga/pull/37

I've updated this, so we don't use arrays here either. Hope that does the trick.

**Comment by widhalmt** [comment]
That's a big one. Great!

**Pull request merged**
